# Generated by Django 2.2.10 on 2020-02-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Pub_date', models.DateTimeField(verbose_name='registration date')),
                ('Address', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=30)),
            ],
        ),
    ]
